<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9uvoxo1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9uvoxo1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9uvoxo1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9uvoxo1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9uvoxo1\App_KernelDevDebugContainer([
    'container.build_hash' => '9uvoxo1',
    'container.build_id' => '06686212',
    'container.build_time' => 1677247181,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9uvoxo1');
